
name не должен браться из тела дто, который передается в запросе, он должен брать значение из того, что возвратит метод parse


бонусы должны учитываться с capabilities

прописать логику если способ оплаты family, то id должен быть none


на витрине метод не меняется, в качестве параметров нужно передать значения согласно спецификации


конечный пункт `patchApiClientOrdersOrderidPaymentmethod` должен возвращать URL и идентификатор заказа в ответе как было реализовано в методе на создание заказа? - точно нет, сам посмотрел


Посмотреть библиотеку тапир, посмотреть как берутся хэдэры из запроса

Посмотреть как реализованы другие запросы в роуте

OrderStatus или в StatusDTO добавить новый параметр phone
clientId - UUID в OrderParameteres
profileId - также получить из заказа

или  StatusDTO 

Не нужно лишнее посылать из запроса, а лучше все брать из заказа

На витрине все остается также, нужно изменить логику в коре

Что-то добавить в Ordersparameteres или как-то так класс называется

OrderParameters

Туда возможно и добавить номер телефона



backend@envis-nbg1-4:~$ docker logs -f -n 30 hivetaxi-backend-client-orders-showcase-dev0
2024-06-28 11:37:07,213 | WARN  | s0-io-4                          | PoolManager                      | [s0] Detected a keyspace change at runtime (<none> => client_orders). This is an anti-pattern that should be avoided in production (see 'advanced.request.warn-if-set-keyspace' in the configuration).
2024-06-28 11:37:12,659 | INFO  | io-compute-13                    | GracefulShutdownConsumer         | Starting 'localization' consumer
2024-06-28 11:37:12,664 | INFO  | io-compute-1                     | GracefulShutdownConsumer         | Starting 'client-migration-orders' consumer
2024-06-28 11:37:12,666 | INFO  | io-compute-11                    | GracefulShutdownConsumer         | Starting 'client-migration-orders-history' consumer
2024-06-28 11:37:12,671 | INFO  | io-compute-10                    | GracefulShutdownConsumer         | Starting 'driver-location-on-order' consumer
2024-06-28 11:37:15,461 | INFO  | io-compute-2                     | MainF                            | Started HTTP server for 0.0.0.0:9210
2024-06-28 11:37:37,241 | WARN  | io-compute-5                     | client-orders-showcase-sttp      | Request: PATCH http://5.75.145.40:9200/api/client/orders/993000000057137/payment-method, took: 0.064s, response: 500 Internal Server Error, headers: server: envoy, date: Fri, 28 Jun 2024 11:37:37 GMT, content-type: application/json, x-envoy-upstream-service-time: 37, transfer-encoding: chunked, body: {"code":"GLA_INTERNAL_SERVER_ERROR"}
2024-06-28 11:37:37,250 | WARN  | io-compute-5                     | OrdersProgram                    | Request returned with an api error InternalError(GLA_INTERNAL_SERVER_ERROR)
2024-06-28 11:37:37,291 | ERROR | io-compute-5                     | Http4sDefaultServerLog           | Exception when handling request: PATCH /api/client/mobile/v2/orders/993000000057137/payment-method, by: PATCH /api/client/mobile/v2/orders/{orderId}/payment-method, took: 634ms
java.lang.IllegalArgumentException: None of the mappings defined in the one-of output: one of(status code (400) {body as application/json (UTF-8)}|status code (404) {body as application/json (UTF-8)}), is applicable to the value: InternalError(GLA_INTERNAL_SERVER_ERROR). Verify that the type parameters to oneOf are correct, and that the oneOfVariants are exhaustive (that is, that they cover all possible cases).
        at sttp.tapir.server.interpreter.EncodeOutputs.applySingle(EncodeOutputs.scala:72)
        at sttp.tapir.server.interpreter.EncodeOutputs.apply(EncodeOutputs.scala:16)
        at sttp.tapir.server.interpreter.EncodeOutputs.applyPair(EncodeOutputs.scala:31)
        at sttp.tapir.server.interpreter.EncodeOutputs.apply(EncodeOutputs.scala:18)
        at sttp.tapir.server.interpreter.ServerInterpreter$$anon$3.apply(ServerInterpreter.scala:219)
        at sttp.tapir.server.interpreter.ServerInterpreter$$anon$2.$anonfun$onDecodeSuccess$2(ServerInterpreter.scala:202)
        at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.$anonfun$warn$4(Slf4jLoggerInternal.scala:99)
        at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.isWarnEnabled(Slf4jLoggerInternal.scala:67)
        at run$ @ region.client.orders.showcase.Main$.run(Main.scala:5)
        at delay @ sttp.client3.impl.cats.CatsMonadError.eval(CatsMonadError.scala:19)
        at map @ sttp.client3.impl.cats.CatsMonadError.map(CatsMonadError.scala:9)
        at delay @ sttp.client3.impl.cats.CatsMonadError.eval(CatsMonadError.scala:19)
        at map @ sttp.client3.impl.cats.CatsMonadError.map(CatsMonadError.scala:9)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at modify @ fs2.internal.Scope.close(Scope.scala:262)

2024-06-28 11:38:15,330 | WARN  | io-compute-4                     | client-orders-showcase-sttp      | Request: PATCH http://5.75.145.40:9200/api/client/orders/993000000057137/payment-method, took: 0.034s, response: 500 Internal Server Error, headers: server: envoy, date: Fri, 28 Jun 2024 11:38:15 GMT, content-type: application/json, x-envoy-upstream-service-time: 23, transfer-encoding: chunked, body: {"code":"GLA_INTERNAL_SERVER_ERROR"}
2024-06-28 11:38:15,330 | WARN  | io-compute-4                     | OrdersProgram                    | Request returned with an api error InternalError(GLA_INTERNAL_SERVER_ERROR)
2024-06-28 11:38:15,334 | ERROR | io-compute-4                     | Http4sDefaultServerLog           | Exception when handling request: PATCH /api/client/mobile/v2/orders/993000000057137/payment-method, by: PATCH /api/client/mobile/v2/orders/{orderId}/payment-method, took: 63ms
java.lang.IllegalArgumentException: None of the mappings defined in the one-of output: one of(status code (400) {body as application/json (UTF-8)}|status code (404) {body as application/json (UTF-8)}), is applicable to the value: InternalError(GLA_INTERNAL_SERVER_ERROR). Verify that the type parameters to oneOf are correct, and that the oneOfVariants are exhaustive (that is, that they cover all possible cases).
        at sttp.tapir.server.interpreter.EncodeOutputs.applySingle(EncodeOutputs.scala:72)
        at sttp.tapir.server.interpreter.EncodeOutputs.apply(EncodeOutputs.scala:16)
        at sttp.tapir.server.interpreter.EncodeOutputs.applyPair(EncodeOutputs.scala:31)
        at sttp.tapir.server.interpreter.EncodeOutputs.apply(EncodeOutputs.scala:18)
        at sttp.tapir.server.interpreter.ServerInterpreter$$anon$3.apply(ServerInterpreter.scala:219)
        at sttp.tapir.server.interpreter.ServerInterpreter$$anon$2.$anonfun$onDecodeSuccess$2(ServerInterpreter.scala:202)
        at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.$anonfun$warn$4(Slf4jLoggerInternal.scala:99)
        at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.isWarnEnabled(Slf4jLoggerInternal.scala:67)
        at run$ @ region.client.orders.showcase.Main$.run(Main.scala:5)
        at delay @ sttp.client3.impl.cats.CatsMonadError.eval(CatsMonadError.scala:19)
        at map @ sttp.client3.impl.cats.CatsMonadError.map(CatsMonadError.scala:9)
        at delay @ sttp.client3.impl.cats.CatsMonadError.eval(CatsMonadError.scala:19)
        at map @ sttp.client3.impl.cats.CatsMonadError.map(CatsMonadError.scala:9)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
        at modify @ fs2.internal.Scope.close(Scope.scala:262)



Должны три параметра телефон, профиль и хлокатион добавляться в базу. Методом partch. 
Завернуть профиль айди в either t через метод fold , как вариант

Завернуть в leftSemiflatTap - профиль айди

и брать переменную лог как на примерах на коре, своя не нужна.



в базу данных ничего добавлять не надо

Логи на витрине и коре работают по разному


OrderStatusActor в котором мы конвертим в StatusDTO из Horder
в StatusDto добавили телефон, профиль, хлокатион

а как устанавливать значения данные , откуда-то они должны браться же

вспомнить как реализовывал с добавлением картинок, также 

После же надо как то записать в базу данных с новыми значениями




Ошибки:
при смене оплаты на карточку, в name нет названия карточки, а в базе есть:

скидывается на наличку, если менять на невалидный способ оплаты карточкой, допустим убрать в способе оплаты id. Именно если id указываешь неправильное, то менятся способ оплаты на кеш. Если же не передаешь name,  то нормально меняется способ оплаты. Если не указываешь вовсе id, то он не перикидывает в cash.
Точно происходит ошибка с карточкой в методе parseRefs, точно там, на этой строчке:

paymentMethod = PaymentMethod.parse(paymentMethodKind, paymentMethodId, settings.cardPaymentAllowed) или в loadPaymentMethod.

если что посмотреть как это реализовано просто при создании заказа

Все таки кажется падает в кэш в parse методе
тоже самое происходит и при способе оплаты фамили

![[Снимок экрана 2024-07-18 150341 2.png]]

по бонусам не может тратить их если у него их меньше 250
посмотреть как реализована оплата бонусами в просто создании заказа